# 1 Этап: Cборка проекта
FROM node:22-alpine AS builder

WORKDIR /client

COPY package.json .
RUN npm install --legacy-peer-deps
# Устанавливаем http-server глобально для использования в production
RUN npm install -g http-server

# Копируем файлы проекта
COPY . .

# Передаем переменные окружения для сборки (ARG передаются как ENV во время сборки)
ARG VITE_BASE_URL
ARG VITE_WS_URL
ARG VITE_BOT_LINK
ARG VITE_BOT_URL
ARG VITE_SUPPORT_EMAIL
ARG VITE_URL_MARK
ARG VITE_TG_HEADER
ARG VITE_YC_HEADER
ARG VITE_WS_CHATS
ARG VITE_WS_COMPL
ARG VITE_WS_LIKES
ARG VITE_WS_MATCH
ARG VITE_WS_MSGS
ARG VITE_INITIAL_ENDPOINT
ARG VITE_SET_GEO_ENDPOINT
ARG VITE_BILLING_ENDPOINT
ARG VITE_ADMINE_ENDPOINT
ARG VITE_LIKES_ENDPOINT
ARG VITE_LIKES_UNREAD
ARG VITE_LIKES_READED
ARG VITE_ADMINE_BLOCK
ARG VITE_ADMINE_UNBLOCK
ARG VITE_ADMINE_PRO
ARG VITE_ADMINE_CMPLS
ARG VITE_UPLOAD_PHOTO
ARG VITE_DELETE_PHOTO
ARG VITE_LOG_ENDPOINT
ARG VITE_REG_ENDPOINT
ARG VITE_CHATS_ENDPOINT
ARG VITE_CHATS_METADATA
ARG VITE_CHATS_MSG
ARG VITE_CHATS_ADD_MSG
ARG VITE_CHATS_MEDIA_ENDPOINT
ARG VITE_CHATS_READ_ENDPOINT
ARG VITE_CHATS_TYPING_ENDPOINT
ARG VITE_CHATS_UNREAD
ARG VITE_CHATS_CREATE_WITH_PSYCH
ARG VITE_CHATS_ASSIGN_PSYCH
ARG VITE_PSYCH_ENDPOINT
ARG VITE_PSYCH_CHECK
ARG VITE_PSYCH_FIND
ARG VITE_PSYCH_AVAL
ARG VITE_PSYCH_GEN_TOKEN
ARG VITE_PSYCH_VALID_TOKEN
ARG VITE_PSYCH_UPL_PHOTO
ARG VITE_PSYCH_DEL_PHOTO
ARG VITE_PSYCH_ACTIVATE
ARG VITE_PSYCH_DEACTIVATE
ARG VITE_VIDEO_ENDPOINT
ARG VITE_VIDEO_UPL
ARG VITE_VIDEO_SAVE
ARG VITE_VIDEO_MY
ARG VITE_VIDEO_SHORTS_FEED
ARG VITE_VIDEO_SHORTS_LIKE
ARG VITE_VIDEO_SHORTS_VIEW
ARG VITE_VIDEO_SHORTS_SERCH
ARG VITE_REDIS
ARG VITE_REDIS_KEY_ENDPOINT
ARG VITE_REDIS_EXPIRE
ARG VITE_REDIS_HASH_ENDPOINT
ARG VITE_REDIS_ZSET_ENDPOINT
ARG VITE_REDIS_COUNT
ARG VITE_REDIS_KEYS
ARG VITE_REDIS_CLEANUP
ARG VITE_REDIS_TTL
ARG VITE_MSGS_ENDPOINT
ARG VITE_MSGS_UPLOAD_ENDPOINT
ARG VITE_MSGS_MEDIA_ENDPOINT
ARG VITE_MSGS_TYPING_ENDPOINT
ARG VITE_MSGS_READ_ENDPOINT
ARG VITE_USER_ENDPOINT
ARG VITE_USER_DEL_ENDPOINT
ARG VITE_USER_DEL_SELF
ARG VITE_USER_PUBLIC
ARG VITE_USER_QUESTS
ARG VITE_USER_SEARCH
ARG VITE_COMPLS_ENDPOINT
ARG VITE_COMPLS_UPT_ENDPOINT
ARG VITE_COMPLS_STATS
ARG VITE_FQ_MEDIA_LINK
ARG VITE_EP_MEDIA_LINK
ARG VITE_USER_STATUS
ARG VITE_CAPTURE_KEY
ARG VITE_CAPTURE_MODE
ARG VITE_HELP_INTERESTS_ENDPOINT
ARG VITE_HELP_PLANS_ENDPOINT
ARG VITE_HELP_CITYES_ENDPOINT
ARG VITE_HELP_REGIONS_ENDPOINT
ARG VITE_HELP_GLOB_COMPLAINTS_ENDPOINT
ARG VITE_HELP_DESC_COMPLAINTS_ENDPOINT
ARG VITE_PLANS_GET_ENDPOINT
ARG VITE_PLANS_SET_ENDPOINT

# Устанавливаем переменные окружения для сборки
ENV VITE_BASE_URL=$VITE_BASE_URL
ENV VITE_WS_URL=$VITE_WS_URL
ENV VITE_BOT_LINK=$VITE_BOT_LINK
ENV VITE_BOT_URL=$VITE_BOT_URL
ENV VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL
ENV VITE_URL_MARK=$VITE_URL_MARK
ENV VITE_TG_HEADER=$VITE_TG_HEADER
ENV VITE_YC_HEADER=$VITE_YC_HEADER
ENV VITE_WS_CHATS=$VITE_WS_CHATS
ENV VITE_WS_COMPL=$VITE_WS_COMPL
ENV VITE_WS_LIKES=$VITE_WS_LIKES
ENV VITE_WS_MATCH=$VITE_WS_MATCH
ENV VITE_WS_MSGS=$VITE_WS_MSGS
ENV VITE_INITIAL_ENDPOINT=$VITE_INITIAL_ENDPOINT
ENV VITE_SET_GEO_ENDPOINT=$VITE_SET_GEO_ENDPOINT
ENV VITE_BILLING_ENDPOINT=$VITE_BILLING_ENDPOINT
ENV VITE_ADMINE_ENDPOINT=$VITE_ADMINE_ENDPOINT
ENV VITE_LIKES_ENDPOINT=$VITE_LIKES_ENDPOINT
ENV VITE_LIKES_UNREAD=$VITE_LIKES_UNREAD
ENV VITE_LIKES_READED=$VITE_LIKES_READED
ENV VITE_ADMINE_BLOCK=$VITE_ADMINE_BLOCK
ENV VITE_ADMINE_UNBLOCK=$VITE_ADMINE_UNBLOCK
ENV VITE_ADMINE_PRO=$VITE_ADMINE_PRO
ENV VITE_ADMINE_CMPLS=$VITE_ADMINE_CMPLS
ENV VITE_UPLOAD_PHOTO=$VITE_UPLOAD_PHOTO
ENV VITE_DELETE_PHOTO=$VITE_DELETE_PHOTO
ENV VITE_LOG_ENDPOINT=$VITE_LOG_ENDPOINT
ENV VITE_REG_ENDPOINT=$VITE_REG_ENDPOINT
ENV VITE_CHATS_ENDPOINT=$VITE_CHATS_ENDPOINT
ENV VITE_CHATS_METADATA=$VITE_CHATS_METADATA
ENV VITE_CHATS_MSG=$VITE_CHATS_MSG
ENV VITE_CHATS_ADD_MSG=$VITE_CHATS_ADD_MSG
ENV VITE_CHATS_MEDIA_ENDPOINT=$VITE_CHATS_MEDIA_ENDPOINT
ENV VITE_CHATS_READ_ENDPOINT=$VITE_CHATS_READ_ENDPOINT
ENV VITE_CHATS_TYPING_ENDPOINT=$VITE_CHATS_TYPING_ENDPOINT
ENV VITE_CHATS_UNREAD=$VITE_CHATS_UNREAD
ENV VITE_CHATS_CREATE_WITH_PSYCH=$VITE_CHATS_CREATE_WITH_PSYCH
ENV VITE_CHATS_ASSIGN_PSYCH=$VITE_CHATS_ASSIGN_PSYCH
ENV VITE_PSYCH_ENDPOINT=$VITE_PSYCH_ENDPOINT
ENV VITE_PSYCH_CHECK=$VITE_PSYCH_CHECK
ENV VITE_PSYCH_FIND=$VITE_PSYCH_FIND
ENV VITE_PSYCH_AVAL=$VITE_PSYCH_AVAL
ENV VITE_PSYCH_GEN_TOKEN=$VITE_PSYCH_GEN_TOKEN
ENV VITE_PSYCH_VALID_TOKEN=$VITE_PSYCH_VALID_TOKEN
ENV VITE_PSYCH_UPL_PHOTO=$VITE_PSYCH_UPL_PHOTO
ENV VITE_PSYCH_DEL_PHOTO=$VITE_PSYCH_DEL_PHOTO
ENV VITE_PSYCH_ACTIVATE=$VITE_PSYCH_ACTIVATE
ENV VITE_PSYCH_DEACTIVATE=$VITE_PSYCH_DEACTIVATE
ENV VITE_VIDEO_ENDPOINT=$VITE_VIDEO_ENDPOINT
ENV VITE_VIDEO_UPL=$VITE_VIDEO_UPL
ENV VITE_VIDEO_SAVE=$VITE_VIDEO_SAVE
ENV VITE_VIDEO_MY=$VITE_VIDEO_MY
ENV VITE_VIDEO_SHORTS_FEED=$VITE_VIDEO_SHORTS_FEED
ENV VITE_VIDEO_SHORTS_LIKE=$VITE_VIDEO_SHORTS_LIKE
ENV VITE_VIDEO_SHORTS_VIEW=$VITE_VIDEO_SHORTS_VIEW
ENV VITE_VIDEO_SHORTS_SERCH=$VITE_VIDEO_SHORTS_SERCH
ENV VITE_REDIS=$VITE_REDIS
ENV VITE_REDIS_KEY_ENDPOINT=$VITE_REDIS_KEY_ENDPOINT
ENV VITE_REDIS_EXPIRE=$VITE_REDIS_EXPIRE
ENV VITE_REDIS_HASH_ENDPOINT=$VITE_REDIS_HASH_ENDPOINT
ENV VITE_REDIS_ZSET_ENDPOINT=$VITE_REDIS_ZSET_ENDPOINT
ENV VITE_REDIS_COUNT=$VITE_REDIS_COUNT
ENV VITE_REDIS_KEYS=$VITE_REDIS_KEYS
ENV VITE_REDIS_CLEANUP=$VITE_REDIS_CLEANUP
ENV VITE_REDIS_TTL=$VITE_REDIS_TTL
ENV VITE_MSGS_ENDPOINT=$VITE_MSGS_ENDPOINT
ENV VITE_MSGS_UPLOAD_ENDPOINT=$VITE_MSGS_UPLOAD_ENDPOINT
ENV VITE_MSGS_MEDIA_ENDPOINT=$VITE_MSGS_MEDIA_ENDPOINT
ENV VITE_MSGS_TYPING_ENDPOINT=$VITE_MSGS_TYPING_ENDPOINT
ENV VITE_MSGS_READ_ENDPOINT=$VITE_MSGS_READ_ENDPOINT
ENV VITE_USER_ENDPOINT=$VITE_USER_ENDPOINT
ENV VITE_USER_DEL_ENDPOINT=$VITE_USER_DEL_ENDPOINT
ENV VITE_USER_DEL_SELF=$VITE_USER_DEL_SELF
ENV VITE_USER_PUBLIC=$VITE_USER_PUBLIC
ENV VITE_USER_QUESTS=$VITE_USER_QUESTS
ENV VITE_USER_SEARCH=$VITE_USER_SEARCH
ENV VITE_COMPLS_ENDPOINT=$VITE_COMPLS_ENDPOINT
ENV VITE_COMPLS_UPT_ENDPOINT=$VITE_COMPLS_UPT_ENDPOINT
ENV VITE_COMPLS_STATS=$VITE_COMPLS_STATS
ENV VITE_FQ_MEDIA_LINK=$VITE_FQ_MEDIA_LINK
ENV VITE_EP_MEDIA_LINK=$VITE_EP_MEDIA_LINK
ENV VITE_USER_STATUS=$VITE_USER_STATUS
ENV VITE_CAPTURE_KEY=$VITE_CAPTURE_KEY
ENV VITE_CAPTURE_MODE=$VITE_CAPTURE_MODE
ENV VITE_HELP_INTERESTS_ENDPOINT=$VITE_HELP_INTERESTS_ENDPOINT
ENV VITE_HELP_PLANS_ENDPOINT=$VITE_HELP_PLANS_ENDPOINT
ENV VITE_HELP_CITYES_ENDPOINT=$VITE_HELP_CITYES_ENDPOINT
ENV VITE_HELP_REGIONS_ENDPOINT=$VITE_HELP_REGIONS_ENDPOINT
ENV VITE_HELP_GLOB_COMPLAINTS_ENDPOINT=$VITE_HELP_GLOB_COMPLAINTS_ENDPOINT
ENV VITE_HELP_DESC_COMPLAINTS_ENDPOINT=$VITE_HELP_DESC_COMPLAINTS_ENDPOINT
ENV VITE_PLANS_GET_ENDPOINT=$VITE_PLANS_GET_ENDPOINT
ENV VITE_PLANS_SET_ENDPOINT=$VITE_PLANS_SET_ENDPOINT

RUN npm run build
RUN npm run minify || echo "minify skipped"

# 2 Этап: Запуск сервера
FROM node:22-alpine AS product

WORKDIR /client

# Копируем только собранные файлы
COPY --from=builder /client/dist ./dist
# Копируем простой Node.js сервер
COPY server.js ./

EXPOSE 4177

# Запускаем простой Node.js сервер
CMD ["node", "server.js"]
